version: '3.8'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DB_HOST=database
    command: bash -c 'while !</dev/tcp/database/27017; do sleep 1; done; node app.js'
    depends_on:
      - database

  database:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
